# Generated by Django 4.2.20 on 2025-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dl21gihhj/image/upload/v1745158564/samples/landscapes/nature-mountains.jpg', null=True, upload_to='events_images/'),
        ),
    ]
