# Generated by Django 4.2.20 on 2025-05-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dl21gihhj/image/upload/v1745158564/samples/landscapes/nature-mountains.jpg', max_length=300, null=True, upload_to='events_images/'),
        ),
    ]
