# Generated by Django 5.1.7 on 2025-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags_alter_tag_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/default.png', null=True, upload_to='blog_images/'),
        ),
    ]
