# Generated by Django 4.2.20 on 2025-04-28 18:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[blog.models.validate_no_bad_words]),
        ),
    ]
