# Generated by Django 5.2 on 2025-05-14 10:51

import blog.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default=blog.models.get_random_blog_image, max_length=255, verbose_name='blog'),
        ),
    ]
